### ISSUE TITLE
S3 bucket names should be globally unique

### ISSUE THREAD

**Issue by mahantesh-yugen** [Yugen-ai/canso-data-plane-k8s-cluster-tf#20]
[S3 Bucket Naming Rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) states that Bucket names must be unique across all AWS accounts.

The bucket names used [here](https://github.com/Yugen-ai/canso-data-plane-k8s-cluster-tf/blob/main/canso-dataplane-configs/s3/auto.tfvars#L1) have to be unique for each data plane set in any account.

**Comment by ashishYugen** [comment]
https://github.com/Yugen-ai/canso-data-plane-k8s-cluster-tf/pull/21
